name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: sudo apt-get update
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
